FilmStoreExam/Controllers/ActorsController.cs
using FilmStoreExam.Interfaces;
using FilmStoreExam.Models;
using FilmStoreExam.Models.Pages;
using Microsoft.AspNetCore.Mvc;

namespace FilmStoreExam.Controllers
{
    public class ActorsController:Controller
    {
        private readonly IActor _actors;
        private readonly IProduct _products;
        public ActorsController(IActor actors, IProduct products)
        {
            _actors = actors;
            _products = products;
        }

        public IActionResult Index(QueryOptions options)
        {
            ViewBag.Products = _products.GetAllProducts().ToList();
            var actors = _actors.GetActors(options);
            return View(actors);
        }
        [HttpPost]
        public IActionResult AddActor(Actor actor)
        {
            _actors.AddActor(actor);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult EditActor(Actor actor)
        {
            ViewBag.EditId = actor.Id;
            return View(nameof(Index), _actors.GetAllActors());
        }
        [HttpPost]
        public IActionResult DeleteActor(Actor actor)
        {
            _actors.RemoveActor(actor);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult UpdateActor(int id)
        {
            ViewBag.Products = _products.GetAllProducts();
            ViewBag.Actors = _actors.GetAllActors();
            return View(id == 0 ? new Actor() : _actors.GetActor(id));
        }
        [HttpPost]
        public IActionResult UpdateActor(Actor actor)
        {
            _actors.UpdateActor(actor);
            return RedirectToAction(nameof(Index));
        }
    }
}

FilmStoreExam/Controllers/CategoriesController.cs
using FilmStoreExam.Interfaces;
using FilmStoreExam.Models;
using FilmStoreExam.Models.Pages;
using Microsoft.AspNetCore.Mvc;

namespace FilmStoreExam.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategory _categories;

        public CategoriesController(ICategory categories)
        {
            _categories = categories;
        }

        [HttpGet]
        public IActionResult Index(QueryOptions options)
        {
            return View(_categories.GetCategories(options));
        }
        [HttpPost]
        public IActionResult AddCategory(Category category)
        {
            _categories.AddCategory(category);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult EditCategory(long id)
        {
            ViewBag.Editid = id;
            return View(nameof(Index), _categories.GetAllCategories());
        }
        [HttpPost]
        public IActionResult UpdateCategory(Category category)
        {
            _categories.UpdateCategory(category);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult DeleteCategory(Category category)
        {
            _categories.DeleteCategory(category);
            return RedirectToAction(nameof(Index));
        }
    }
}

FilmStoreExam/Views/Shared/PageOptions.cshtml
<div class="container-fluid mt-2">
    <div class="row m-1">
        <div class="col"></div>
        <div class="col-1">
            <label class="col-from-label">Поиск</label>
        </div>
        <div class="col-3">
            <select form="pageform" name="options.searchpropertyname" class="form-control">
                @foreach (string s in ViewBag.searches as string[])
                {
                    <option value="@s" selected="@(Model.Options.SearchPropertyName == s)">
                        @(s.IndexOf('.') == -1 ? s : s.Substring(0, s.IndexOf('.')))
                    </option>
                }
            </select>
        </div>
        <div class="col">
            <input form="pageform" class="form-control" name="options.searchterm" value="@Model.Options.SearchTerm" />
        </div>
        <div class="col-1 text-right">
            <button form="pageform" class="btn btn-secondary" type="submit">Поиск</button>
        </div>
        <div class="col"></div>
    </div>
    <div class="row m-1">
        <div class="col"></div>
        <div class="col-1">
            <label class="col-form-label">Сортировка</label>
        </div>
        <div class="col-3">
            <select form="pageform" name="options.OrderPropertyName" class="form-control">
                @foreach (string s in ViewBag.sorts as string[])
                {
                    <option value="@s" selected="@(Model.Options.OrderPropertyName == s)">
                        @(s.IndexOf('.') == -1 ? s : s.Substring(0, s.IndexOf('.')))
                    </option>
                }
            </select>
        </div>
        <div class="col btn-check form-check-inline">
            <input form="pageform" type="checkbox" name="Options.DescendingOrder" id="Options.DescendingOrder" class="form-check-input"
                   value="true" checked="@Model.Options.DescendingOrder" />
            <label class="form-check-label">Сортировка по убыванию</label>
        </div>
        <div class="col-1 text-right">
            <button form="pageform" class="btn btn-secondary" type="submit">Сортировка</button>
        </div>
        <div class="col"></div>
    </div>
</div>

FilmStoreExam/Views/Shared/Pages.cshtml
<form method="get" class="form-inline m-3" id="pageform">
    <button name="options.CurrentPage" value="@(Model.CurrentPage - 1)"
            class="btn btn-outline-primary @(!Model.HasPreviousPage ? "disabled" : "")" type="submit">
        Назад
    </button>

    @for (int i = 1; i <= 3 && i <= Model.TotalPages; i++)
    {
        <button name="options.CurrentPage" value="@i" type="submit"
            class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")">
            @i
        </button>
    }
    @if (Model.CurrentPage > 3 && Model.TotalPages - Model.CurrentPage >= 3)
    {
        @:...
        <button class="btn btn-outline-primary active">@Model.CurrentPage</button>
    }
    @if (Model.TotalPages > 3)
    {
        @:...
        @for (int i = Math.Max(4, Model.TotalPages - 2); i <= Model.TotalPages; i++)
        {
            <button name="options.CurrentPage" value="@i" type="submit"
            class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")">
                @i
            </button>
        }
    }
    <button name="options.CurrentPage" value="@(Model.CurrentPage + 1)" type="submit"
            class="btn btn-outline-primary @(!Model.HasNextPage ? "disabled":"")">
        Вперед
    </button>
  
    <select name="options.PageSize" class="my-form-control">
        @foreach (int val in new int[] { 10, 25, 50, 100 })
        {
            <option value="@val" selected="@(Model.PageSize == val)">@val</option>
        }
    </select>
    <input type="hidden" name="options.CurrentPage" value="1" />
    <button type="submit" class="btn btn-outline-primary">Изменить размер страницы</button>
</form>


<style>
    .my-form-control {
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.25rem;
        transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    }
</style>

FilmStoreExam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FilmStoreExam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FilmStoreExam.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FilmStoreExam</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="d-flex navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Категории</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="Index">Актёры</a>
                            </li>
                        }
                        <li class="d-flex my-auto align-self-end">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <p class="my-auto mx-2">@User.Identity.Name</p>

                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input type="submit" value="Выход" />
                                </form>
                            }
                            else
                            {
                                <a asp-controller="Account" asp-action="Login">Вход</a>
                                <a asp-controller="Account" asp-action="Register">Регистрация</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FilmStoreExam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>